- segmentation/utils/segmentation_utils.py
- segmentation/utils/segmentation_utils_test.py
The recent refactor resulted in a bug where only the first FOV's worth of cells was getting extracted. This PR fixes is. Closes #100
> Fix bug in single cell extraction

- segmentation/utils/signal_extraction.py
- segmentation/utils/signal_extraction_test.py
- segmentation/utils/synthetic_spatial_datagen.py
- segmentation/utils/synthetic_spatial_datagen_test.py
Addresses and closes #157.
Now that we've implemented a first pass of channel-level synthetic data generation, it's time to look into more detailed signal extraction techniques.
Currently, we're naively summing across all channels. As #157 outlines, we should start by working on more nuanced signal extraction techniques that can lend us more information.
> Extending Signal Extraction

- ark/analysis/spatial_analysis_test.py
The no enrichment cases for channel and cluster enrichment currently rely on a completely random generation of an array, which can cause the p-values and especially the z-scores to fail. For now, adding a random seed for that test will do the trick.
Duplicate tests for no enrichment also appeared, so we'll need to update those to test for p_neg (which was missing).
I still think it would be useful to implement a smarter way to randomly generate no_enrich tests in the near future without having to set a random seed, but for now, this should do the trick.
> No enrichment randomized and testing patch

- .travis.yml
- requirements-test.txt
- requirements.txt
Consolidates all of the relevant test dependencies into a separate requirements-test.txt file. This makes it simpler to install locally, and avoids having to specify each in the .travis.yml file.
> Dedicated requirements file for testing

- ark/segmentation/marker_quantification.py
- ark/segmentation/marker_quantification_test.py
- ark/utils/segmentation_utils_test.py
This closes #175. The wrong index was being passed for the nuclear compartment. Because our test data was essentially identical between nuclear IDs and cell_ids, this wasn't caught. I fixed the indexing issue, and modified the test data so that it is passed different values for cell and nuclear labels, which can then be compared to make sure the assignment was done correctly.
> Extraction bugfix

- ark/utils/data_utils.py
- ark/utils/data_utils_test.py
A few data_utils functions don't have test functions: combine_point_directories, stitch_images, and split_img_stack. Additionally, stitch_images and split_img_stack also don't have documentation. This PR addresses it and closes #71.
> Stitching test functions

- ark/segmentation/marker_quantification.py
- templates/Deepcell_Postprocessing.ipynb
Addresses and closes #120.
The current variable names are not that descriptive when it comes to cell size normalization and arcsinh transformation. We've gotten several questions from others about what exactly normalization and transformation meant. Renaming the variables and adding some more comments should do the trick.
> Make cell size normalization and arcsinh transformation clearer

- .github/pull_request_template.md
- docs/contributing.md
Adds documentation for how to contribute to our project. Closes #195
> Make contributing file

- docs/conf.py
- requirements.txt
The most recent readthedocs config for some reason throws a color error with the nbsphinx extension. We won't be needing Jupyter notebook support for our .md files anyways, so we'll need to delete them.
Change the extensions variable in conf.py to not include nbsphinx and nbsphinx_link.
> Remove nbsphinx from conf.py

- ark/segmentation/marker_quantification.py
- ark/segmentation/marker_quantification_test.py
**If you haven't already, please read through our [contributing guidelines](https://github.com/angelolab/ark-analysis/tree/master/docs/contributing.md) before opening your PR**
Modifies regionprops so that the properties are modifiable (in theory) by the user. This allows different props to be specified if desired. 
Closes #214, which was removing the first cell when background wasn't present in the image
Adds centroid location of each cell as a default output to the pipeline. 
Separated out the names of the regionprops properties being passed to regionprops, and the names of the resulting attributes. This makes it easier to track what we're passing to regionprops, and what we're adding to the final CSV. These …
> Modifiable regionprops args

- ark/utils/segmentation_utils.py
- ark/utils/segmentation_utils_test.py
**If you haven't already, please read through our [contributing guidelines](https://github.com/angelolab/ark-analysis/tree/master/docs/contributing.md) before opening your PR**
Currently, when we match nuclei to cells, we don't require that the nucleus be smaller than the cell. If the nuclear segmentation has errors, this can result in non-biological readouts. 
This PR adds the option to separate out nuclei that are larger than a cell, and relabel the portion that falls within a cell, to remove this issue
Added a function that takes a nuclear mask and a cell mask, and relabels any nuclei that have pixels outside of the boundaries of the corresponding cell they map to. 
Still need to integrate …
> Binning nuclear labels

- ark/segmentation/marker_quantification.py
- ark/segmentation/marker_quantification_test.py
Forgot to push this commit before merging previous PR. This adds the functionality from #222 into the signal extraction function
> Add nuclei_split to main function

- setup.py
Now that we've actually set up .travis.yml to deploy to PyPI, we now need to officially send a release to PyPI so our package will be able to be downloaded via pip.
- Bump the version number to 1.0.0
- Separate the version number into a constant in `setup.py` so it can be easily located and updated when needed
- Add a `download_url` param in `setup.py` which points to the .tar.gz file generated on a new release, this file needs to be created separately by opening a new release on the repo
- Make sure to tag this commit on merge into master. We should tag this commit with the version number. So in this case, the tag associated with this commit should be 1.0.0.
- Remember: to officially make this …
> Bump version number to 0.2.4 (prepare initial deployment)

- setup.py
The reason our PyPI project is still not deploying correctly is that the `name` argument in the call to `setup` of `setup.py` is incorrect. Currently, it is set to `'ark'`, which sadly, is already taken as a name on PyPI. This is why we got a 403 error on our last merge into master: we obviously didn't have the credentials to release a new version to that project.
We need to change `name` to `'ark-analysis'` because that's the name of our project on PyPI. Also, bump the version number so nothing conflicts.
If you're curious what `ark` is on PyPI, see this: https://pypi.org/project/ark/. It was a static website generator. However, it seems like the repo no longer exists. Aww, I wanted to see it …
> Fix name in setup call of setup.py

- Dockerfile
- docs/_rtd/virtualenv.md
Addresses and closes #202. We add documentation for creating virtual environments and installing our package via `pip` now that it has been deployed to PyPI. This will provide a foundation for users with more technical expertise to use ark.
Content is added to `docs/_rtd/virtualenv.md` to generate documentation on ReadTheDocs about virtual environment creation with a `conda` setup and a `pip` installation of `ark-analysis`.
This PR may also need to address an issue which prevents all the `install_requires` packages in `setup.py` from installing on top of running `pip install ark-analysis`. We could get around this by simply listing in this page which additional packages need to be installed. …
> Add virtual environment documentation

- ark/segmentation/signal_extraction.py
- ark/segmentation/signal_extraction_test.py
- ark/utils/synthetic_spatial_datagen.py
- ark/utils/synthetic_spatial_datagen_test.py
A mini PR to address and close #189.
Dramatically reduce and shorten the comments and function names in `synthetic_spatial_datagen`, and by extension, `signal_extraction`.
> Refactor synthetic_spatial_datagen

- docs/conf.py
A very mini-PR to stop generating documentation for `test_utils.py`. Addresses and closes #251.
We simply modify `conf.py` in `docs` to ignore every filename containing test in its name, not just those with a test suffix.
If there are any other functions we don't want to generate documentation for, please feel free to let me know and we can address that in this PR too.
> Remove documentation for test_utils.py

- ark/utils/spatial_analysis_utils.py
A very basic PR to address a simple yet crucial bug in `calculate_enrichment_stats` where we change `p_pos` to strictly greater than in checking. Addresses and closes #129.
We change `>=` to `>` in the calculation.
> Fix calculation of p_pos in calcuate_enrichment_stats

- ark/utils/load_utils.py
- ark/utils/load_utils_test.py
Addresses and closes #271. Someone recently encountered a bug in `load_imgs_from_mibitiff` in which an empty list of `mibitiff_files` (which subsequently leads to an empty list of `fovs`) caused the loading process to freak out. We need to properly address this so the error message is clear.
In addition to adding a basic check for an empty `mibitiff_files` list in the function, also add `data_dir` validation where needed.
> Add empty list validation for mibitiff loading

- ark/analysis/spatial_analysis.py
- ark/analysis/spatial_analysis_test.py
- ark/utils/test_utils.py
Addresses and closes #265. Also addresses and closes #266. We add a more robust method to verify that the markers in `all_channel_data` and `marker_thresholds` are the same between the two, and we ensure that they are ordered consistently as well. This only applies for channel enrichment.
Use set equality to check if the markers are the same, and reindexing to enforce order.
This is an extremely strict way of handling the various different types of `marker_thresholds` and `all_channel_data` values the user may pass in. From personal experience, expect all sorts of messes in this regard. This method may be a bit too strict, so I'm open to other ideas.
> Fix marker ordering errors and verification for channel enrichment

- .travis.yml
- setup.py
Addresses #242. This PR may require more work after it is merged in because we can only see the final results after a merge into master.
Now that Omer has completely integrated deepcell with ark-analysis, we need to bump the version number. However, another issue needs to be addressed: running `pip install ark-analysis` will only install `ark-analysis`, but not any of the other dependencies.
We use `deepcell-toolbox` as a guiding point for our changes.
It seems like `deepcell-toolbox` specifically implemented some of their changes because they need to install `deepcell` as well. I'm not sure how much is actually applicable to us, it may potentially not work. If so, we'll need to open another PR …
> Bump version number and ensure requirements.txt are installed properly on pip install

- templates/Segment_Image_Data.ipynb
Addresses and closes #285. By extension, addresses and closes #284. When more than 3 channels are specified, plot overlaying will fail. This is because we're trying to visualize the un-summed arrays, but we need to visualize the summed arrays across nuclear and membrane channels.
`generate_deepcell_input` already handles the summing, so we just need to read that data from the directory `deepcell_input` and pass that to our overlay instead.
> Fix Segment_Image_Data plot overlay

- ark/utils/deepcell_service_utils.py
To add logging for `deepcell_service_utils` to describe the current stage of the pipeline. closes #283 
Added logging when: creating the zip file, calling kiosk-client, and extracting the tif files from the output of deepcell. 
kiosk-client writes its own logs (using Python `logging` module). Maybe it is worth thinking if/how to integrate with it so we can show these logs in the pipeline (for example, currently there will be no indication in our pipeline if there was a problem when uploading the files to deepcell server).
> Add status updates to deepcell_service_utils

- ark/utils/data_utils.py
To avoid the repeating warning: 'X.tif is a low contrast image'. closes #260 
This warning is raised when saving the preprocessed .tif images to the deepcell_input dir.
Setting the optional parameter `check_contrast` of skimage.io.imsave to false.
> ignore low_contrast warning

- docs/conf.py
- docs/index.rst
Addresses and closes #296. Our documentation has a few textual artifacts that don't need to be there and are confusing because they are empty headings. This PR focuses on nuking all of that.
We add a function in `conf.py` to make the documentation pages prettier and easier to follow along.
If there is anything else we need to nuke from these pages (ex. removing all the repetitive `ark.analysis`, `ark.segmentation`, and `ark.utils`), I can further edit `conf.py` to do that.
> Remove unnecessary headings from documentation

- ark/utils/deepcell_service_utils.py
To change the implementation in`create_deepcell_output` so that the generated zip file will have a smaller size.
[Bug fix (closes #301)]
`create_deepcell_output`generates the zip file using the zipfile module (https://docs.python.org/3/library/zipfile.html#zipfile-objects). the default value for the `compression` parameter in zipfile.ZipFile is `zipfile.ZIP_STORED` (uncompressed archive member). I changed the value to `zipfile.ZIP_DEFLATED` (the usual ZIP compression method). 
After changing this parameter, the zip file created by the notebook is the same size as one created manually.
> compression parameter

- .coveragerc
- ark/segmentation/marker_quantification.py
- ark/segmentation/marker_quantification_test.py
- ark/utils/load_utils_test.py
- ark/utils/misc_utils_test.py
- ark/utils/segmentation_utils_test.py
- ark/utils/spatial_analysis_utils.py
- ark/utils/spatial_analysis_utils_test.py
Addresses and closes #256. We have quite a few lines that run important validation checks prior to performing an operation. While it's not feasible to test all of these, we should certainly try to do so where we can.
We improve our testing functions to cover more cases, mostly that we're throwing errors properly.
Is there a need to address the coverage issues in `test_utils.py`? I don't think so since these are mostly for test functions. We should tell `coveralls` to disregard this file when computing coverage.
Also, is it worth writing test functions for `plot_utils.py`?
> Address coverage issues

- ark/segmentation/marker_quantification.py
Addresses and closes #309 . The ```generate_cell_table``` was producing a ValueError if the base images were in any format other than ```'int16```, and now it can handle all of the formats that the load_images functions can handle.
I added a ```dtype``` argument (with default = 'int16', which is the default for the load_images utility functions) to ```generate_cell_table```. This argument is then fed directly to the util.load_images function calls within the function.
> Add dtype as an argument to generate_cell_table

- templates/Segment_Image_Data.ipynb
Addresses and closes #304. Because we're reading in the summed nuclear and membrane channels, we need to make sure that the channel list we pass in actually corresponds to that (and not the original list of channels). This PR patches that up.
We simply change `xr_channel_names` to `nuclear_summed` and `membrane_summed`.
> Fix channel names list for reading back in tifs from deepcell_input_dir

- ark/utils/deepcell_service_utils.py
- ark/utils/deepcell_service_utils_test.py
Addresses and closes #322 . This change allows users to add a scale value as input to create_deepcell_output, which rescales the data before prediction.
I added ```scale``` as an input argument to the ```create_deepcell_output``` and ```run_deepcell_task``` functions in the util module. The default value is 1.0 for both functions. Finally, before the value is submitted to the server, it is converted from float to string, as required by the deepcell API. I figured that most users would intuitively provide the scale value as a float.
> Add scale argument to create_deepcell_output and run_deepcell_task functions

- requirements-test.txt
- requirements.txt
- setup.py
Because the `attrs` library updated 12-13 hours ago, `treq` also had to be updated, and by extension, `kiosk-client`. `master` is currently failing because we need to update our `requirements.txt` to match the version of `kiosk-client`.
Simply bump the requirement in `requirements.txt` and `setup.py`.
Is it best that we don't assert requirement ranges for `kiosk-client` for the time being?
> Bump kiosk-client requirement

- docs/_rtd/contributing.md
Fixes the headings in `contributing.md`. They are all h2 headings, meaning that RTD will format all of them to appear in the `Getting Started` section, which we don't want. We need to change all but the top heading to h3 to prevent this.
See above.
> Fix contributing.md headings so they don't all display in sidebar

- ark/utils/spatial_analysis_utils.py
Optimizes data types in `spatial_analysis_utils.py` for memory usage.  Closes #337  
- distance matrices where float64, and are now float32
- `close_num` and `close_num_rand` were long's (int32 on most hardware), and are now uint16
- binarized distance matrices where int8's, and are now uint8's
- `np.sum()`'s on integer types where given `dtype` arguments to prevent default promotion to int64
There are probably more memory optimizations that could be performed, but let's deal with those as needed.
> Optimize data types in spatial analysis utils

- ark/segmentation/marker_quantification.py
- ark/segmentation/marker_quantification_test.py
- ark/segmentation/signal_extraction.py
- ark/segmentation/signal_extraction_test.py
- templates/Segment_Image_Data.ipynb
Allows different extraction functions to be called from the notebooks.  Functions were already written, but couldn't be accessed by users.  Closes #157 
Users can pass a string denoting the type of extraction they want to use.  Additionally, for extractions which require additional arguments/parameters, kwargs have been added to facilitate generalized 'passing down' of these additional arguments.  The arguments of the extraction functions were made identical to facilitate general callability via dictionary in `signal_extraction`
Some more test functions could be added, along with an example in the segmentation notebook.  Lmk what your thoughts are on that front.
> Extraction options

- .travis.yml
- Dockerfile
- ark/utils/load_utils.py
- ark/utils/plot_utils.py
- ark/utils/test_utils.py
- ark/utils/tiff_utils.py
- ark/utils/tiff_utils_test.py
- docs/conf.py
- requirements-nodeps.txt
- setup.py
- templates/Segment_Image_Data.ipynb
Some users have had trouble building the docker due to mibilib's strict library dependencies.  We've attempted to address this before, but problems persist.  This PR removes the mibilib dependency, while preserving basic mibitiff support.
Calls to `mibilib.tiff` are no longer used; `tiff_utils.read_mibitiff` and `tiff_utils.write_mibitiff` replace its usages.
Only a limited subset of mibitiff is supported, not the entire specification.  All that's been implemented is the basic functionality required to read/write channel data from/to mibitiffs.
> Removes mibilib dependency

- ark/utils/deepcell_service_utils.py
- ark/utils/deepcell_service_utils_test.py
- docs/conf.py
- requirements.txt
- setup.py
Replaces kiosk-client with direct calls to deepcell API.  This bypasses the kiosk client upload bug described in issue #302 so smaller zip files don't need to be created; we can just upload one.  Consequently closes #302 
Replaces kiosk-client usage in `deepcell_service_utils.py` with direct calls to deepcell's api.  This more closely mimics direct user interaction with deepcell.org.
Might want to check with Van Valen lab on how stable their deepcell API will be.
> Auto upload patch

- requirements.txt
- setup.py
I forgot to add the `requests` dependency to `requirements.txt` in PR #369.  Travis passed then only because `requests` is a sub-dependency of one of our `requirements-test.txt` dependencies, meaning it gets installed as if it were a regular requirement.
Adds `requests` as dependency in requirements and setup
> adds requests dependency

- setup.py
There's a typo in `setup.py` that prevents docker from building.  Travis lets this build since it doesn't rely on setup.py while docker does.
Adds a lonely comma
mostly some shame tbh.  I suppose we could look into changing our travis testing to necessitate using `setup.py` somehow, but, regardless, it's probably best to just remember to try new setups/requirements related builds locally before hastily submitting pr's @ackagel  (I checked and this one builds fine)
> adds missing comma in setup.py

- Dockerfile
- ark/phenotyping/consensus_cluster.R
- ark/phenotyping/run_trained_som.R
- ark/phenotyping/som_utils.py
- ark/phenotyping/som_utils_test.py
- ark/utils/notebooks_test_utils.py
- start_docker.sh
- templates/example_flowsom_clustering.ipynb
Addresses and closes #364. The next step in the clustering pipeline is to add Candace's meta-clustering process, which involves using consensus clustering to analyze the data associated with each SOM cluster assignment.
We utilize R's `ConsensusClusterPlus` library and add a new R file `consensus_cluster.R` as a runner. To compute the average channel values across all `fovs`, we add a preprocessing algorithm to `som_utils.py`: `compute_cluster_avg`.
> Add consensus clustering process

- ark/segmentation/marker_quantification.py
- ark/segmentation/marker_quantification_test.py
- ark/utils/segmentation_utils.py
The current split_nuclei logic first modifies the nuclear segmentation mask, and then uses that modified mask to extract signal. However, it doesn't provide that modified mask to the regionprops function, which results in a mismatch between the outputs from the two
I passed in the modified nuclear segmentations to the regionprops function so that the outputs match up. I also switched the min_size value to match up with the current min_size from Mesmer
We don't pass these modified nuc masks back to the user, but given that this …
> Split nuclei bugfix

- ark/utils/io_utils.py
- ark/utils/io_utils_test.py
- ark/utils/load_utils.py
- ark/utils/spatial_analysis_utils.py
The current validate_paths function assumes that the user is within the docker and all paths are prefixed with /data. However, as we start to use these functions elsewhere and pip install the library, we don't want this assumption to necessarily be true. 
I've modified this function to give the option of dropping the /data prefix requirement, and updated all calls to validate_paths which are outside of a jupyter notebook to use this new logic.
> Modify validate_paths to work outside docker

- ark/phenotyping/create_som_matrix.R
- ark/phenotyping/run_trained_som.R
- ark/phenotyping/som_utils.py
- ark/phenotyping/som_utils_test.py
- ark/utils/load_utils.py
- ark/utils/notebooks_test.py
- ark/utils/notebooks_test_utils.py
- templates/example_flowsom_clustering.ipynb
Addresses and closes #384. A lot of the processes are currently being done per `fov`. Instead, we transition to a "per set of `fov`" workflow.
- Preprocessing: instead of reading in the entire image array, read in just a few `fovs` at a time
- Clustering: run the trained SOM on multiple `fovs` at a time rather than on a single `fov`.
See the issue page.
> Batch the FlowSOM process

- ark/segmentation/regionprops_extraction.py
- ark/segmentation/regionprops_extraction_test.py
The custom regionprops functions don't do any validation of the inputs. In general this is fine, since they come from the base regionprops function. However, minor_axis_length seems to fairly regularly return a value of zero, which causes errors. 
Add error checking and return NaN for division by zero, rather than an error.
> Prevent divide by zero

- setup.py
Bumps version to 0.2.9. This incorporates the small error checking PRs I added in, and will allow the pip-installable version of the repo to work for generating figures for the Mesmer paper.
> Bump version to 0.2.9

- ark/phenotyping/consensus_cluster.R
- ark/phenotyping/som_utils.py
- ark/phenotyping/som_utils_test.py
- templates/example_flowsom_clustering.ipynb
Currently, we're only saving the consensus cluster to SOM cluster mapping table. We actually want to use that mapping to assign the consensus clusters to each pixel in our dataset.
We pass in more arguments to `consensus_cluster.R` and write the results to a new directory: `pixel_mat_consensus`.
> Fix consensus clustering so it assigns hclust values to each pixel

- ark/segmentation/marker_quantification.py
- ark/segmentation/marker_quantification_test.py
Closes #401. Currently, we index the cell table when computing single compartment features with all the features (including multi compartment features), which throws a warning. This warning likely will become an error in the future, so best to patch this up now.
We don't append `regionprops_multi_comp` to `regionprops_names` until we actually need to compute multi compartment features. This means that we also need to explicitly append multi comp features to `marker_counts` prior to computing them.
> Fix single compartment indexing for morphology computations

- ark/phenotyping/consensus_cluster.R
- ark/phenotyping/create_som_matrix.R
- ark/phenotyping/run_trained_som.R
- ark/phenotyping/som_utils_test.py
Addresses and closes #416. We add the metadata columns to both the SOM and consensus clustered data so it will be easy to access for users.
We change the way we read in the `feather` dataframes from subsetting on just channel columns to reading in everything. We then use the `markers` vectors to subset the data for computational purposes, but we add additional columns to the full data.
> Add metadata columns to SOM cluster and consensus cluster data

- templates/Segment_Image_Data.ipynb
Closes #387. Now that nuclear property extraction is all up and running, we need to make it easier to users to request nuclear extraction in the notebook.
Add a cell that allows users to set `nuclear_counts = True`.
> Add option to set nuclear_counts in Segment_Image_Data

- templates/Segment_Image_Data.ipynb
Closes #423. `Segment_Image_Data.ipynb` does not make it obvious that the image scaling factor can be adjusted. We add an option to allow the user to easily override the default value of 1.0.
Add a cell before the call to `create_deepcell_output` to allow the user to set the `scale` argument.
> Add option to change scale factor for cell segmentation

- README.md
- start_docker.sh
Closes #391. If the `requirements.txt` file is changed, Docker will need to be rebuilt. However, many users won't know to do this. To prevent confusion, we should automatically rebuild Docker for them if `requirements.txt` has been changed.
We update `start_docker.sh` to run the `docker build` command automatically if the file has been changed within the last day. Tough luck if the user misses the deadline, but I think it's a generous one (the user is likely going to immediately start Docker after a new pull anyways).
> Automatically rebuild Docker if requirements.txt modified

- requirements.txt
Closes #448. We need to update the `cryptography` library so that changes in the new version (updated around 10:20 AM on August 24, 2021), which includes the need for an extra dependency, take effect.
Change `requirements.txt`.
We may need to explicitly include the `Rust` library if it's not installing correctly.
> Bump cryptography to 3.4.8

- ark/utils/data_utils.py
- ark/utils/plot_utils.py
This PR allows high level functions in the jupyter notebook to handle images that are of a different datatype than the default int16.
I added ```dtype``` as an argument for the ```data_utils.generate_deepcell_input``` and ```plot_utils.create_overlay functions```. The dtype argument is then passed to the load_imgs functions from load_utils.
> added dtype arg to generate_deepcell_input and create_overlay functions

- ark/analysis/dimensionality_reduction_test.py
- ark/analysis/visualize_test.py
- ark/settings.py
- ark/spLDA/processing.py
- ark/spLDA/processing_test.py
- ark/utils/segmentation_utils_test.py
- ark/utils/spatial_lda_utils.py
- ark/utils/test_utils.py
- requirements.txt
This PR adds functions which compute various exploratory metrics for determining (1) a potential radius to use for spatial-LDA featurization and (2) an appropriate number of topics for training/inference.  In addition, a function was added which generates a typical cell table with default column names.  Some columns also have data which is randomly generated for testing purposes.
To get a rough idea of an appropriate number of topics, we leverage the speed of K-means clustering and compute diagnostic metrics on the result.  This includes standard clustering metrics like inertia and silhouette score.  It also includes more specialized metrics like the gap statistic which requires bootstrapping the data.  
For making …
> Spatial-LDA exploratory metrics and test utils.

- ark/utils/google_drive_utils.py
The `run_local_server` oauth2 strategy doesn't play nice with jupyter/docker anymore for some reason.  Switching to the `run_console` strategy, avoids this problem.
> changes to run_console strategy for gdrive oauth2

- ark/utils/data_utils.py
- ark/utils/data_utils_test.py
- templates/Segment_Image_Data.ipynb
Closes #470. A bug in `generate_deepcell_input` defaulted the `img_sub_folder` value passed into `load_imgs_for_tree` to always be `'TIFs'`. We need it to accept the `img_sub_folder` value passed into `generate_deepcell_input` instead.
In addition to changing this, we also change the default value for `img_sub_folder` of `generate_deepcell_input` to be `None` instead of `'TIFs'`.
> Allow generate_deepcell_input to accept other img_sub_folder values (including None) for non-MIBItiff inputs

- ark/mibi/qc_comp.py
- templates_qc/example_qc_metric_eval.ipynb
Runs user specify to download for QC analysis may contain Moly points. `example_qc_metric_eval.ipynb` is currently not equipped to handle this, so we add functionality in to prevent the download of Moly points.
A check is added in `download_mibitracker_data` to remove any FOVs from the download which do not contain the channels desired. Since all other images will contain the full set of channels, this will remove any Moly points from the mix.
> Patch MibiTracker download to prevent downloading of channels from Moly points

- ark/analysis/spatial_analysis.py
- ark/analysis/spatial_analysis_test.py
- ark/utils/_bootstrapping.pyx
- ark/utils/spatial_analysis_utils.py
- ark/utils/spatial_analysis_utils_test.py
Corrects bootstrapping randomization to asymmetric pairing scheme.  Closes #485.
Currently building off of the speed up PR.  Most changes are to the arguments of the relevant functions.  Still runs at about the same speed, although there's still a small speed up which could be gained by assuring that the marker/cell_type undergoing dictionary storage is the larger of the two.  This was guaranteed in the symmetric version, but now requires (at a minimum) a `rand_rows_or_cols` flag to reap the full benefits of said speed-up.
Still need to correct the test functions' arguments
> removes self-counting and asymmetrizes randomization scheme

- ark/utils/load_utils.py
- ark/utils/load_utils_test.py
Updates load_imgs_from_tree to support variable image sizes of arbitrary size, as specified by the user
Changes the variable_sizes boolean arg to a max_img_size integer arg specifying the length of the largest image that will be loaded. This is in contrast to hardcoding in 1024 as the largest image size, which is what the function currently does
> remove hardcoded variable_sizes arg

- .travis.yml
- README.md
- setup.py
- start_docker.sh
Addresses one part of #502. Instead of having the user build the Docker locally every time, we want to push a new Docker image on a tagged commit. In this way, the user can simply download the latest Docker image.
We piggyback off https://github.com/vanvalenlab/deepcell-tf/blob/ad2b019fa912a7d417964429e4c4142abd0d3175/.travis.yml#L72.
Add a new entry to the `jobs` section of `.travis.yml` called `docker_deploy` which handles pushing to Docker Hub.
We won't be able to find potential bugs until we push an actual tagged commit. Additionally, some of the following issues may need to be resolved with a 2nd PR:
- We'll need to add our Docker username and password as `$DOCKER_USERNAME` and …
> Deploy a Docker image using Travis

- ark/utils/io_utils.py
- ark/utils/io_utils_test.py
This PR closes #360. It adds an `exact_match` function parameter to the `list_folders` function. In addition it adds specific tests for
the case where `exact_match` is set to True.
1. The same case from `list_files` was used.
2. Instances of using `.sort()` within `assert` statements were replaced with `sorted()`, as `.sort()` returns `None`. 
There could be more instances of using asserts with `.sort()`
instead of `sorted()`.
For example:
```python
a = [6,5,4,3]
assert a.sort() == [3,4,5,6]
```
Would not pass as `a.sort()` …
> Added exact_match to list_folders

- ark/utils/io_utils.py
- ark/utils/io_utils_test.py
Closes #506. The purpose of this PR is to add an option for the user to ignore hidden directories in `io_utils::list_folders` and hidden files in `io_utils::list_files`.
When `ignore_hidden == True`, the functions ignore all files and folders which start with a `.`. Defaults to `True`.
None.
> Added option to ignore hidden files and directories

- templates_ark/example_pixel_clustering.ipynb
The order of the file path creation for channel files contained in FOV folder subdirectories got swapped due to merging issues. The line:
```
chan_file = os.path.join(
fovs[0], img_sub_folder, io_utils.list_files(os.path.join(tiff_dir, img_sub_folder, fovs[0]), substrs=['.tif', '.tiff'])[0]
)
```
should be
```
chan_file = os.path.join(
fovs[0], img_sub_folder, io_utils.list_files(os.path.join(tiff_dir, fovs[0], img_sub_folder, substrs=['.tif', '.tiff'])[0]
)
```
See above
> Patch channel file path creation for pixel cluster overlay

- README.md
- docs/_rtd/development.md
- start_docker.sh
Closes #516.
Placed instructions for building the Docker Image locally in `docs/_rtd/development.md`. Removed the logic which rebuilds the image if changes are detected in `start_docker.sh`.
Added instructions based off Installation instructions in the `README.md`. Deleted the logic directly.
None atm.
> Docker Image build instructions, removed rebuild logic

- ark/utils/data_utils.py
Closes #556. There was an issue merging the indexing PR into `master` which reverted:
```
coordinates = x_coords * img_data.shape[1] + y_coords
```
to
```
coordinates = x_coords * img_data.shape[0] + y_coords
```
We should revert this back.
See above.
> Revert index back to 1 when getting shape of `pixel_cluster_mask`

- start_docker.sh
When `start_docker.sh` was modified to handle multiple flag cases, the control statement to run `update_notebooks.sh` was removed. This needs to be added back in.
See above.
> Put call to `update_notebooks.sh` back into `start_docker.sh`

- README.md
- ark/phenotyping/pixel_consensus_cluster.R
There shouldn't be any more references to Docker needing to rebuild locally now that we have Dockerhub integration.
This necessitates the removal of the line indicating that Docker would rebuild with the `-u` or `--update` flag pass to `start_docker.sh`.
> Delete references to Docker locally rebuilding in `README.md`

- ark/utils/metacluster_remap_gui/metaclustergui.py
- start_docker.sh
Closes #536 and closes #550. There are issues with the current hard-coded width and height settings for the visualization that cause the channel names to overlap and/ or the metacluster heatmap to become small and illegible. For now, we hard code new values. Depending on how we move forward, we may also add a programmatic way to compute these.
The issue lies with:
```
width_ratios = [
int(self.mcd.cluster_count / 7),
self.mcd.cluster_count,
self.mcd.metacluster_count,
]
height_ratios = [6, self.mcd.marker_count, 3, 3]
subplots = plt.subplots(
4, 3,
gridspec_kw={
'width_ratios': width_ratios,
'height_ratios': height_ratios},
figsize=(self.width, 6),
)
```
We double the width of `self.mcd.metacluster_count`, double …
> Address metacluster GUI height and width issues

- ark/phenotyping/som_utils.py
- ark/phenotyping/som_utils_test.py
Because the `channel_norm` and `pixel_norm` files were changed from `.json` to `.feather` format in `pixel_mat_dir`, they now get read in along with the `fov` files when retrieving them for verification in this line:
```
data_files = io_utils.list_files(data_path, substrs='.feather')
```
In some cases, this can cause `channel_norm.feather` to be read in as a FOV file by mistake. This needs to be prevented.
Add two `.remove` statements after the aforementioned line to prevent `channel_norm.feather` and `pixel_norm.feather` from interfering. Because these are hard-coded names set in `create_pixel_matrix`, the naming will not cause any issues.
> Remove `channel_norm.feather` and `pixel_norm.feather` from `cluster_pixels` verification

- docs/_rtd/development.md
Closes #593.
Added instructions on getting ark-analysis and running on M1 for development.
This runs under the Intel to Arm transition layer, as we update to Python 3.8, we might want to look at updating libraries to get a native Arm implementation.
> Added documentation for setting up development on M1

- ark/utils/misc_utils.py
- ark/utils/misc_utils_test.py
Closes angelolab/toffy#120. Fixes a dtype iteration issue.
Added a check to allow `str` to become an iterable as `[str]`. Added several tests for the following objects: `list`, `np.array`, and the following types `str`, `bool`, `int`.
None atm.
> Singleton list of dtype fix

- ark/utils/deepcell_service_utils.py
Closes #587. Changes the default zip file size so that large cohorts don't cause an error. 
Changed default from 100 to 10
> Change default zip size

- ark/segmentation/marker_quantification.py
- ark/segmentation/marker_quantification_test.py
Updates the segmentation pipeline to work with images without any cells. 
Check for number unique objects in segmentation mask. If there aren't any cells, skips the `regionprops` extraction and just returns an empty df. Also adds tests to prevent future reversions
> Allow segmentation pipeline to handle blank images

- setup.py
This fixes an issue where version `0.3.00` does not exist, and pip / conda will try to install this version and fails.
Adjusts the version from `0.3.00` to `0.3.1`. This should fix the installing it locally.
None ATM.
> VERSION 0.3.00 -> 0.3.1

- ark/phenotyping/som_utils.py
- ark/phenotyping/som_utils_test.py
- ark/utils/notebooks_test_utils.py
- templates_ark/example_pixel_clustering.ipynb
Closes #612. The `dtype` argument currently isn't propagated through to the channel and pixel normalization functions, causing the `load_imgs_from_tree` calls to attempt to load the images using the default `int16` type. This will throw a warning if the images were of type `float32` regardless of if the user passed `float32` to `create_pixel_matrix`.
Add `dtype` with a default argument of `int16` to both `calculate_channel_percentiles` and `calculate_pixel_intensity_percentile`. Explicitly pass the `dtype` argument received by `create_pixel_matrix` to these functions.
> Add `dtype` argument to channel and pixel norm functions

- setup.py
`ark-analysis` will not install properly via PyPI, the issue seems to reside with the `PKG_FOLDER` variable.
Set `PKG_FOLDER` the same as it is in `toffy`.
Need to adjust ark-analysis requirement in angelolab/toffy#132, and make sure it can install properly.
> PKG_FOLDER variable in `setup.py` cannot find `requirements.txt` due to filepath issue.

- requirements.txt
Closes #614. Currently, the Python 3.7 image is built using the latest `matplotlib` version (3.5.x), which introduced several bugs to colorbar scaling. Several issues related to this are still open on the `matplotlib` repo, so it's best that we don't use this version for our purposes.
Pin `requirements.txt` at version `3.4.2`.
The Python 3.7 Docker image is still problematic because we haven't rebuilt it with `matplotlib==3.4.2` yet. Before this is done, users should continue using the Python 3.6/latest image.
Additionally, we should keep close watch of `matplotlib` updates on colorbar usage. Once they resolve the issue, we can matplotlib back to the most recent version.
> Pin matplotlib at 3.4.3 in requirements.txt to prevent colorbar scaling issue

- ark/utils/metacluster_remap_gui/metaclustergui.py
Closes #630. The way the toolbar is set up, the meta cluster renaming textbox/drop-down menu can get cut off on the far right. This needs to be pushed further to the center.
Adjust the toolbar's `layout.justify_content` setting to `'center'`.
> Ensure the meta cluster rename drop down menu for remapping doesn't get cut off

- ark/utils/data_utils.py
- ark/utils/data_utils_test.py
Closes #521.
Edits the `save_fov_images` function so the pixel clustering notebook saves overlays images that can be loaded into photoshop.
Could instead add the saving dtype as a default arg to the function, if that's something you think we'd use.
> Save fov images as int16

- ark/analysis/spatial_analysis_test.py
- ark/utils/test_utils.py
Adds basic coverage tests for context dependent spatial enrichment analysis
Uses existing enrichment testing infrastructure to test for the errorless operation of enrichment functions when provided context arguments.
Functionality tests should be added in a future PR.  Using tools like pytest-cases + fixtures to clean up cell table generation in`test_utils.py` would really clean up (at a minimum) `spatial_analysis_tests.py`, and would make adding functionality tests (context dependence, feature distance-hack, etc) much easier.
> Context tests

- ark/phenotyping/som_utils.py
- ark/phenotyping/som_utils_test.py
- ark/utils/notebooks_test_utils.py
- templates_ark/example_pixel_clustering.ipynb
Closes #619. Prior to pixel clustering, users may need to filter out non-nuclear marker signal from the nucleus and vice-versa for nuclear marker signal.
Add a function `filter_with_nuclear_mask` to `som_utils` which runs this process. The code in #619 provides most of the functionality, however we'll need to make two modifications:
- Ensure `seg_dir is not None` prior to running. Users may run pixel clustering without segmentation labels, however they will not be able to run this function if that's the case because it relies on the `_feature_1.tiff` files.
- Ensure `channel` defaults to `None` in the notebook and function. This is the easiest guard against errors caused by running all the cells at once in the …
> Add nuclear filtering functionality to pixel clustering pipeline

- ark/phenotyping/som_utils.py
- ark/phenotyping/som_utils_test.py
Closes #599. The underlying issue is if the user provides a different set of channels on a `pixel_output_dir` that has an existing `channel_norm.feather` computed on a different set of channels.
We need to ensure that the set of channels provided when loading in an existing `channel_norm.feather` match the `channels` argument set-wise. If they don't, then we simply re-compute and re-save.
The same needs to be done for `pixel_norm.feather`. We store a checkpoint during the `channel_norm.feather` check to ensure this can happen seamlessly for the pixel norm too.
> Ensure channel norm and pixel norm files get re-computed if a new set of channels are provided

- README.md
Closes #671.
Adds a Badge that has the version of the current Docker Image. It fetches the latest by release date (currently that's v0.4.1, but it'll auto-update to vX.Y.Z` as new releases get made).
None ATM.
> Added Docker Vesion Badge

- docs/_rtd/windows_setup.md
Closes #687. Adds steps the user can follow if `wsl` throws a `docker not found` error, or if they don't receive output running `wsl` commands.
New section is called `Addressing docker not found` under `Setting up the repo`.
> Add section to troubleshoot WSL distro issues

- ark/utils/data_utils.py
- ark/utils/data_utils_test.py
- ark/utils/notebooks_test_utils.py
- templates_ark/1_Segment_Image_Data.ipynb
Closes #701. If a user specifies a cohort with variable size images, `generate_deepcell_input` will fail because it attempts to batch images of different sizes into one `xarray`. Users should be able to generate this input regardless of the image sizes specified.
Because it was observed that batching doesn't improve speed over a per-FOV iteration, we'll change it to the latter. This will be a fail-safe against loading multiple variable-sized images.
> Handle variable size images for Deepcell input generation

- .travis.yml
- Dockerfile
- start_docker.sh
- start_jupyter.sh
Allows users to update+reinstall ark codebase within docker with `-u` flag. closes #703 
Adds the `ARK_UPDATE` environment variable, which is set to 0 or 1 depending on if the `-u` or `--update` flag is set.  If true, the docker will reinstall ark-analysis before running the jupyter lab command.  This is done by replacing the `CMD jupyter lab ...` line in `Dockerfile` with a call to the new `start_jupyter.sh` script.
I think I can neatly fit #710 in here too, but this is ready for testing in the mean time.
> Docker local changes

- ark/utils/data_utils.py
- ark/utils/data_utils_test.py
Closes #719. The pixel mask generation function assumes square MIBI images, however we're now seeing cohorts being run on rectangular images that will make this assumption fail. This is a problem for pixel mask generation in particular, as it's flattening and reindexing method will throw an error under.
We need to change the indexing multiplier to be the number of columns. Previously, we could assume the number of rows equalled the number of columns, so the row axis size was used for convenience sake of accessing the first available axis. 
@jonhsussman may have additional input.
> Support rectangular images for pixel mask generation

- templates_ark/example_pairwise_spatial_enrichment.ipynb
Closes #724. 
Add the arg `match_substring` to the `load_imgs_from_dir()` call to make sure only the specified feature images are loaded. @cwalker8 tested and approved
> Edit spatial enrichment notebook to only load in desired features

- ark/utils/data_utils.py
- ark/utils/data_utils_test.py
Closes #722. With very large images with a high number of cells, `relabel_segmentation` will take hours to complete because of the way boolean indexing works. Additionally, very large 2-D NumPy arrays can cause cache misses due to the way they're non-contiguously stored in memory.
Using `np.vectorize` provides a significant speed up.
@jonhsussman can you check out this branch and verify that it runs efficiently? When I timed your looped version versus the `np.vectorize` version, the latter ran about 2-2.5x faster, but that was on test data (we unfortunately don't have images of your size on hand at our lab). I can convert this back to a looped version if you find the opposite to be true.
> Speed up `relabel_segmentation`

- ark/analysis/spatial_analysis.py
- ark/analysis/spatial_analysis_test.py
- templates/example_pairwise_spatial_enrichment.ipynb
Addresses part 4 of #720.
Remove `batch_size` as a parameter from both `batch_channel_spatial_enrichment` and `batch_cluster_spatial_enrichment`.
Since these functions are no longer being batched, their names were also changed from `batch_channel_spatial_enrichment` to `generate_channel_spatial_enrichment_stats`, and likewise for cluster enrichment.
> Remove `batch_size` parameter from spatial analysis functions

- README.md
Closes #750 and closes #751. We should have the status of our docs builds in our `README.md`.
Copy the Read the Docs badge generated on its end to the `README.md`.
We will also need to patch up the branch `latest` is pointing at. Currently, it's set to `master`, since we recently renamed `master` to `main`, the `latest` documentation is pointing to a dead branch.
> Add Read the Docs status badge to README

- ark/spLDA/processing.py
- ark/utils/spatial_analysis_utils.py
Closes #566. The inertia and silhouette score computations take a while to complete, so they should have progress bars.
These should be the last progress bars that need to be added to `ark`.
Use `tqdm.notebook` as implemented in other modules.
> Add inertia and silhouette score progress bars for neighborhood analysis notebook

- templates/1_Segment_Image_Data.ipynb
- templates/2_Cluster_Pixels.ipynb
Closes #686.
Remove mentions of MIBItiff in the notebooks and instead use the underlying default `is_mibitiff=False` in the functions.
> Remove mibitiff option in notebooks

- .travis.yml
Fixes a bug that can pop up when a separate `scripts` gets specified in a `job`. This can overwrite the global `script`, which in effect skips the `pytest` runs in the PR.
It's also better to separate `pytest` out into its own job, as it shouldn't be included with the deployment stages. This can help us isolate the `pytest` logs from the deployment logs.
Include a separate `pytest_run` stage.
> Run `pytest` as a separate job to avoid `scripts` from getting overwritten

- ark/phenotyping/pixel_cluster_utils.py
- ark/phenotyping/pixel_cluster_utils_test.py
- ark/phenotyping/pixel_consensus_cluster.R
- ark/phenotyping/run_pixel_som.R
- ark/utils/notebooks_test_utils.py
- templates/2_Cluster_Pixels.ipynb
Closes #771. Adds option to run a non-parallel version of Pixie preprocessing, SOM and meta cluster assignment, and meta cluster renaming.
Add control flow statements handled by a dedicated `multiprocess` argument.
> Make non-parallel loops canon for Pixie

- ark/analysis/spatial_analysis.py
- ark/analysis/spatial_analysis_test.py
Closes #787 
Fixes bug in kmeans neighborhood notebook if excluded_channels is None.
Include check for excluded_channels is None before subsetting data table.
> In k-means neighborhood notebook, fix excluded_channels=None

- ark/phenotyping/cell_cluster_utils.py
- ark/phenotyping/pixel_cluster_utils.py
- ark/segmentation/fiber_segmentation_test.py
- ark/utils/data_utils.py
- ark/utils/data_utils_test.py
- ark/utils/io_utils.py
- ark/utils/io_utils_test.py
- ark/utils/load_utils_test.py
- ark/utils/metacluster_remap_gui/colormap_helper.py
- ark/utils/metacluster_remap_gui/file_reader.py
- ark/utils/misc_utils.py
- ark/utils/plot_utils.py
- ark/utils/spatial_analysis_utils_test.py
- ark/utils/spatial_lda_utils.py
- ark/utils/spatial_lda_utils_test.py
- ark/utils/test_utils.py
Closes #777.
Change `validate_paths` to raise a FileNotFoundError instead of a ValueError, and use the function when appropriate throughout the repo.
When we bump ark to toffy eventually, a lot of the tests will need to be changed to catch the new error type.
> Increase validate paths usage

- ark/segmentation/fiber_segmentation.py
- requirements.txt
- templates/1_Segment_Image_Data.ipynb
Closes #775. Adds csv compression.
Adds an option in Notebook 1 and fiber segmentation notebook for saving the csvs with ZSTD Compression.
None ATM.
> Compressed `csv` Option in Notebook 1

- ark/utils/data_utils.py
- ark/utils/load_utils.py
- ark/utils/load_utils_test.py
Closes #795. Adjusts the tiled image loading function so we can stitch by shape even when loading from toffy fov folders that haven't been renamed to the RnCm format yet
Detailed in design doc #795.
> Adjust load tiled imgs for toffy use

- ark/phenotyping/post_cluster_utils.py
- ark/phenotyping/post_cluster_utils_test.py
- ark/utils/plot_utils.py
- ark/utils/plot_utils_test.py
Closes #809.
Added a parameter to `ark.phenotyping.post_cluster_utils.create_mantis_project` and `ark.utils.plot_utils.create_mantis_dir` which lets users change the name of the segmentation mask suffix.
N/A.
> Added Parameter for Seg Mask Suffix for Mantis

- ark/analysis/spatial_analysis.py
- ark/utils/spatial_analysis_utils.py
Closes #812. Adds a random seed to KMeans clustering in neighborhood analysis to ensure reproducible results.
Pass a `seed` parameter to the cluster metrics and assignment functions of neighborhood analysis, which is analogous with `random_state` in `sklearn.cluster.KMeans` and `pd.DataFrame.sample`.
> Use `random_state` parameter in KMeans clustering for reproducibility

- .coveragerc
- ark/phenotyping/post_cluster_utils.py
- ark/phenotyping/post_cluster_utils_test.py
- ark/settings.py
- ark/utils/io_utils.py
- ark/utils/plot_utils.py
- ark/utils/plot_utils_test.py
- templates/2_Cluster_Pixels.ipynb
- templates/3_Cluster_Cells.ipynb
Closes #842. Using file extensions other than `.tiff` for `seg_suffix` in the Notebooks: Pixel Clustering, Cell Clustering will not work due to hard-coded in extension types. It should be backwards compatible for now.
`seg_suffix` used in Notebooks 2,3 will now work appropriately with `post_cluster_utils.create_mantis_project` and `plot_utils.create_mantis_dir`.
- `seg_suffix` now requires the file extension in addition to the suffix.
- Added the constant `EXTENSION_TYPES` to `ark.settings.py` which contains file extensions for images, archival …
> `seg_suffix` Requires Explicit File Extension

- ark/utils/load_utils.py
Closes #866. Users will now be able to read in files ending in "tif" (one 'f').
Used the `EXTENSION_TYPES` constant to generalize over all major image formats ("tif", "tiff", "png", etc...)
N/A.
> Load Utils - Expanding Acceptable File Types

- ark/phenotyping/cluster_helpers.py
- ark/phenotyping/cluster_helpers_test.py
Closes #887. It's currently not possible to re-run `2_Pixie_Cluster_Pixels` in case the user needs to specify a new subset of markers on the same cohort. This is a common occurrence and should be addressed.
In `PixelSOMCluster.train_som`, add a check to verify the existing weights columns (if applicable) and the provided set of columns match. If they do not, this means a new set of columns was specified and `PixieSOMCluster.train_som` should re-run.
> Ensure pixel SOM training reruns if new markers specified

- ark/phenotyping/cell_cluster_utils.py
- ark/phenotyping/cell_cluster_utils_test.py
- ark/phenotyping/cluster_helpers.py
- ark/phenotyping/cluster_helpers_test.py
- ark/phenotyping/pixel_cluster_utils.py
- ark/phenotyping/pixel_cluster_utils_test.py
- ark/utils/plot_utils.py
This argument was not propagated over to `PixelSOMCluster`, so it would always load in all the FOVs. It should only read the subset of FOVs
Add a param `fovs` to `PixelSOMCluster` constructor to address this. When loading in the subsetted data frames, file names are verified against the `fovs` list provided.
> Ensure `cluster_helpers.PixelSOMCluster` receives the `fovs` argument

- src/ark/phenotyping/pixel_meta_clustering.py
- src/ark/phenotyping/pixel_som_clustering.py
Apparently Windows doesn't like it when you try to `os.rename` something that is an "open process" (causing pixel clustering functions to fail). After much experimenting, seems like the fix is easy. `shutil.move` seems to do the trick.
Change `os.rename` to `shutil.move`. Tested on my computer, Ben's, and MIBIAN.
None
> Change os.rename to shutil.move

- README.md
- start_docker.sh
A new release was created last night, however the `start_docker.sh` and `README.md` files were not updated to include the latest version.
- In `start_docker.sh` bumped `VERSION` to `v0.6.1`
- In `README.md` bumped the git clone instruction to `v0.6.1`
None.
> Next Release `v0.6.1`

- src/ark/analysis/neighborhood_analysis.py
- src/ark/analysis/visualize.py
- templates/Calculate_Mixing_Scores.ipynb
- templates/example_neighborhood_analysis_script.ipynb
Closes #963 and closes #964. 
Passed the `cell_type_col`arg into the appropriate functions, renamed the arg in `create_neighborhood_matrix` from cluster_name_col --> cell_type_col for consistency.
Edited `visualize.draw_heatmap` to save images without cropping, and heatmaps are saved by default now.
Previously, the output files were saved with the same name each time the notebook was run, unless you manually changed them to indicate counts vs freq or a different cell column. Now, the results are saved to a subfolder within the …
> Kmeans notebook minor fixes

- pyproject.toml
- src/ark/analysis/spatial_analysis_utils.py
Maybe fixes #968. 
Changes `n_init` from 'auto' to 10, to keep the algorithm params consistent with the prior default value.
**Note:** I've pinned alpineer temporarily so that the new multiple tiled stitching adjustments made won't apply until a formal PR is opened. A few of the ark stitching functions will need to be tweaked.
Unrelated to #967. I'm still not quite sure what's going on there.
> Set Kmeans parameter to prior default

- src/ark/utils/plot_utils.py
- tests/utils/plot_utils_test.py
Closes #969. Adds the ability to not move segmentation files.
Added a flag to check and see if either `seg_dir` or `seg_suffix_name` are `None`.
Refactored the test to use a fixture, should make it easier to modify now.
N/A.
> Mantis Directory with no segmentation files

- src/ark/utils/deepcell_service_utils.py
Closes #1001. We were using the incorrect keyword (`dataRescale`) to indicate scale of the image, so all segmentations were being done at the default 20x.
Updated the json file we send to the deepcell server to now use `{"jobForm": "scale" = scale}`.
I tested running the segmentation notebook with rescale factor 1 and 0.33 and now get different results.
N/A
> Fix segmentation rescale_factor

- src/ark/utils/deepcell_service_utils.py
- tests/utils/deepcell_service_utils_test.py
Closes #1009. Changes shape of the segmentation masks from 3d to 2d.     (1, 1024, 1024) --> (1024, 1024)
This now allows the images to be stitched in `Image_Stitching.ipynb` without issue.
Squeeze the `ranked_segmentation_mask` before saving it to a tiff. 
> Drop 3rd dimension in segmentation masks

- src/ark/phenotyping/cluster_helpers.py
- src/ark/phenotyping/pixie_preprocessing.py
- tests/phenotyping/pixie_preprocessing_test.py
1. Closes #1016. Implement intermediate saving of per image 99.9th percent values. 
In addition, two small corrections were made to the pixie code.
2. adds a new `channel_percentile_postnorm` argument to `create_pixel_matrix()`, rather than hard coding 0.999.
3. add fix for the edge case where an image has no positive pixels (previously would error out)
(@HPiyadasa ran into this issue when trying to pixels cluster only SMA+ pixels within a mask)
4. Should also close #900.
1. Add image values to quantile_data.csv as they are processed. Also check …
> Pixie percentile saving

- src/ark/phenotyping/cell_som_clustering.py
- src/ark/phenotyping/cluster_helpers.py
- templates/generic_cell_clustering.ipynb
- tests/phenotyping/cell_som_clustering_test.py
- tests/utils/notebooks_test.py
Closes #1000. Make the 99.9 percentile normalization in cell clustering optional.
Adds a `normalize` flag to `train_cell_SOM` and in the CellSOMCluster class which is defaulted to True.
Changing this arg to False will not conduct 99.9 percentile normalization on the data before cell clustering.
N/A
> Optional normalization for generic_cell_clustering.ipynb

- src/ark/analysis/cell_neighborhood_stats.py
- src/ark/analysis/neighborhood_analysis.py
- src/ark/analysis/spatial_analysis_utils.py
- src/ark/analysis/spatial_enrichment.py
- src/ark/segmentation/fiber_segmentation.py
- src/ark/utils/data_utils.py
- src/ark/utils/deepcell_service_utils.py
- src/ark/utils/plot_utils.py
1. Closes #1028. Add current processing FOV name to progress bar output in the ark notebooks.
2. Closes #970. Fix incorrect progress bars that show <100% even though the batch was processed fine.
1. Update the FOV name at start of each code block using `progress_bar.set_postfix(FOV=fov)`.
2. I was able to replicate @HPiyadasa's issue, and it turns out two things could potentially happen with the current code:
- Since we only check the progress every 3 seconds, sometimes we don't always know that the last fov is in progress before getting a "done" …
> Update progress bars

- pyproject.toml
The `tables` dependency is causing issues with pip installing `ark-analysis` and any repos that have it as a dependency (ex. `cell_classification`). This is a dependency we don't need anymore, so it should be removed.
Remove the `tables` dependency.
> Release 0.6.6 without tables dependency

- README.md
- start_docker.sh
Update the `README.md` version to v0.6.6, and ensure `start_docker.sh` also pulls the right version.
v0.6.5 --> v0.6.6.
> Update README from v0.6.5 to v0.6.6

- src/ark/phenotyping/cell_cluster_utils.py
- tests/phenotyping/cell_cluster_utils_test.py
Closes #1046. In certain cases, cells don't contain any pixel clusters. These should not contribute to the cell SOM training.
In `create_c2pc_data`, after `cluster_counts` is fully computed for all FOVs, add a step that drops rows that sum to zero across the pixel cluster expression cols. This propagates over to `cluster_counts_size_norm` (the data that trains the SOM and receives the cluster assignments), since it depends on `cluster_counts`.
> Remove cells that don't have any pixel clusters expressed prior to Pixie

- .github/scripts/get_example_dataset.py
- src/ark/settings.py
- src/ark/utils/plot_utils.py
- templates/2_Pixie_Cluster_Pixels.ipynb
- templates/3_Pixie_Cluster_Cells.ipynb
- tests/utils/example_dataset_test.py
Closes #1045. Without this argument passed to `create_mantis_dir`, there isn't a way to copy the single-channel TIF files over.
Added this as a parameter to the function. Additionally, updated `cell_clustering_params.json` to take in both `tiff_dir` and `img_sub_folder`. The former is purely QOL and the latter is to support the `img_sub_folder` param for the Mantis function in the cell clustering notebook.
> Include `img_sub_folder` as parameter in Mantis calls

- .github/scripts/get_example_dataset.py
- src/ark/settings.py
We've had ongoing issues with HuggingFace, caching, etc. With the new changes to the main branch of HuggingFace this should pull all the recent changes correctly.
Update HuggingFace version and main branch to ensure correctness.
> Update HuggingFace to main

- pyproject.toml
Closes #1055. Improves fiber segmentation results by pinning scikit-image to an older version.
Update pyproject.toml.
Short term solution. Should be looked into for a more permanent fix in the future.
> Pin to scikit-image to v0.19.3

- src/ark/phenotyping/post_cluster_utils.py
- src/ark/utils/plot_utils.py
- templates/2_Pixie_Cluster_Pixels.ipynb
- templates/3_Pixie_Cluster_Cells.ipynb
- templates/4_Post_Clustering.ipynb
- templates/generic_cell_clustering.ipynb
- tests/phenotyping/post_cluster_utils_test.py
- tests/utils/plot_utils_test.py
Closes #669 and closes #1059.  Creates a single top level mantis directory for notebooks 2, 3, and 4, to avoid duplicate files. 
- Set the mantis folder to be created as one subdirectory within the base_dir, rather than within each specific notebook folder.
- Change the output masks from notebook 4 to be named with `_post_clustering_cell_mask` instead of just `_cell_mask` to avoid overwriting notebook 3 cell cluster output files.
- Change the output masks from the generic_cell_clustering notebook to be named `_generic_cell_mask`.
**Remaining …
> Single mantis directory

- src/ark/segmentation/marker_quantification.py
- tests/segmentation/marker_quantification_test.py
Closes #1097. Updates `generate_cell_table` to be compatible with updated ezSeg pipeline when nuclear masks need to be discarded.
By default, the updated `generate_cell_table` loads in all the masks, including nuclear, and adds them to the cell table. For pixel clustering, only the whole cell data is needed, so if `nuclear_counts=False`, this mask type should not appear in the table.
Integration testing with Pixie/Nimbus needed.
> Only load whole cell masks if `nuclear_counts=False` in `generate_cell_table`

- pyproject.toml
- src/ark/segmentation/ez_seg/merge_masks.py
- src/ark/utils/data_utils.py
- templates/anndata_conversion.ipynb
- templates/ez_segmenter.ipynb
- tests/segmentation/ez_seg/merge_masks_test.py
- tests/utils/data_utils_test.py
> 1119 reducing time to merge in merge maskspy wi ez segmenter

- src/ark/phenotyping/cluster_helpers.py
- src/ark/phenotyping/pixel_cluster_utils.py
- src/ark/phenotyping/pixel_som_clustering.py
- tests/phenotyping/pixel_cluster_utils_test.py
- tests/phenotyping/pixel_som_clustering_test.py
During SOM clustering, it is possible in some cases that not all unique clusters discovered during training will be present in the dataset. In these cases, it's too strict for the SOM cluster mapping function to require all the SOM clusters to be represented.
Add an additional parameter to the SOM cluster assignment function that is defaulted to not require all the SOM clusters to be present. This can be explicitly set to revert back to the original format.
The underlying averaging function is also adjusted accordingly.
> Don't require user to have all pixel SOM clusters represented during assignment

- src/ark/segmentation/fiber_segmentation.py
- tests/segmentation/fiber_segmentation_test.py
Fixes bugs in `generate_summary_stats` and `generate_tile_stats`, which was causing all the metric averages for a fiberto be the same at the first metric value. Also set pixel density and fiber values to different variables.
Fix a few silly typos.
Add tests to check for different calculated stats.
N/A
> Fiber stats bugs

- templates/example_neighborhood_analysis_script.ipynb
Closes #1129. 
Fixes `generate_and_save_neighborhood_cluster_masks()` call in the kmeans notebook.
Adds argument keywords to avoid incorrect ordering.
N/A
> Fix kmeans notebook mask generation

- .gitignore
- environment.yml
Fixes an issue with creating conda environments, as there are no `scikit-image` wheels for python 3.11.
Changed the `yml` file and set it to python 3.10.
We should probably update the fiber segmentation filtering function to use the new version of `frangi()`, `scikit-image >=0.20`. The most recent release is on `0.23.1`.
Related Issues:
- #1060
> Change python version in conda env file

- README.md
- start_docker.sh
Ready for a new release.
Updates the README to include the version for the next release `0.7.1`
N/A.
> Next Release 0.7.1

- README.md
Closes #1145. Due to issues users have had trying the Docker setup, it's best for the general public not to use this setup.
Remove anything from the `README.md` about Docker setup. Instead, provide detailed instructions for using `conda` environments and `./start_jupyter.sh`.
> Remove anything Docker related from the README
