Evaluate_Segmentation.py
Watershed.py
caliban_processing.py
change_labels.py
deepcell_postprocessing.py
downsample.py
extract_single_cell_data.py
helper_functions.py
ilastik.py
run_network_preprocessing.py

Merging working into master

---

Watershed.py
deepcell_postprocessing.py
extract_single_cell_data.py
helper_functions.py
subcellular_localization.py

adds in plotting script for evaluating localization fraction of signal

Subcellular metrics integration

---

Evaluate_Segmentation.py

add option for saving dataframe

---

evaluation/compare_segmentation.py
evaluation/evaluate_segmentation.py

add in line plot functionality for mAP across cohort

line plot for mAP

---

helper_functions.py

loads data as channels last to be compatible with deepcell. Also changes tif loader to be default without sub-directory TIF folder

Channels last

---

segmentation/__init__.py

added __init__.py to enable import via pip into other projects

make utils functions importable for other projects

---

segmentation/utils/data_utils.py

modified code to faithfully transmit dtype through helper functions for imaging data with large values

ensure dtype matches input data to avoid overflow

---

.travis.yml
segmentation/utils/data_utils.py
setup.py

Trying out automated upload on new tags

travisCI integration with PyPI

---

.travis.yml
segmentation/utils/data_utils.py
setup.py

Reverts angelolab/segmentation#46

Revert "travisCI integration with PyPI"

---

segmentation/evaluation/evaluate_segmentation.py
segmentation/preprocessing/data_preprocessing.py
segmentation/utils/data_utils.py
segmentation/utils/evaluation_utils.py
segmentation/utils/evaluation_utils_test.py
segmentation/utils/plot_utils.py
segmentation/utils/segmentation_utils.py

Adds test functionality for eval_utils. Closes #65 Closes #22

eval_utils testing

---

.travis.yml
pytest.ini
segmentation/analysis/subcellular_localization.py
segmentation/evaluation/evaluate_segmentation.py
segmentation/utils/data_utils.py
segmentation/utils/data_utils_test.py
segmentation/utils/evaluation_utils.py
segmentation/utils/evaluation_utils_test.py
segmentation/utils/helper_functions.py
segmentation/utils/notebooks_test.py
segmentation/utils/plot_utils.py
segmentation/utils/plot_utils_test.py
segmentation/utils/segmentation_utils.py
segmentation/utils/segmentation_utils_test.py
setup.py

Change travis to use pep8. Also modifies pytest.ini to exclude working directories

Adds pep8 checking to repository

---

scripts/Deepcell_Preprocessing.ipynb

Closes #79. Closes #80. I realized that uint wasn't the problem, it's just an overall signal quality issue

changed NetCDF backend

---

scripts/Deepcell_Postprocessing.ipynb
segmentation/utils/plot_utils.py
segmentation/utils/segmentation_utils.py
segmentation/utils/segmentation_utils_test.py

Adds better testing for watershed. Pulls out CSV saving. Closes #86, closes #85, closes #76

Better testing for watershed

---

segmentation/utils/segmentation_utils.py

Removes issue in postprocessing script that was resulting merges at the border

Watershed bugfix

---

segmentation/preprocessing/data_preprocessing.py
segmentation/utils/segmentation_utils.py
segmentation/utils/signal_extraction_utils.py

Create separate function to extract data from cells

signal extraction

---

segmentation/preprocessing/data_preprocessing.py
segmentation/preprocessing/phenotype_preprocessing.py

Add separate file to track preprocessing steps for phenotype analysis.

phenotype preprocessing

---

segmentation/utils/segmentation_utils.py
segmentation/utils/segmentation_utils_test.py

Adds functionality to either save no TIFs, just summary tifs, or all tifs, to control file sizes for large cohort analyses. Closes #104

Better options for tif saving

---

segmentation/utils/visualize.py
segmentation/utils/visualize_test.py

Added plotting functions and their test functions

Plotting functions

---

segmentation/utils/segmentation_utils.py
segmentation/utils/segmentation_utils_test.py
templates/Deepcell_Postprocessing.ipynb

Abstract Deepcell_Postprocessing.ipynb

---

segmentation/utils/spatial_analysis.py
segmentation/utils/spatial_analysis_utils.py
segmentation/utils/spatial_analysis_utils_test.py

Speeds up previously slow functions in spatial analysis, as referenced in issue #161.  Additionally, will look into generalizing 'cell-label acrobatics' as referenced in issue #130.

Closenum speedup

---

segmentation/utils/spatial_analysis.py
segmentation/utils/spatial_analysis_utils.py
segmentation/utils/spatial_analysis_utils_test.py

Code cleanup 2

---

Dockerfile
README.md
start_docker.sh

This updates the start_docker.sh and Dockerfile with the new repo names. It also updates the Readme

Update docker commands

---

.travis.yml

Turns out my previous change #172 wasn't a great idea, it removes the checkmark from the home page, we can't have that.

add master back to travis

---

.gitignore
ark/analysis/dimensionality_reduction.py
ark/analysis/dimensionality_reduction_test.py
ark/analysis/spatial_analysis_test.py
ark/analysis/visualize_test.py

Addresses and closes #182.
As outlined in the issue, we create a helper function for the dimensionality_reduction function to remove duplicated logic. Additionally, we remove duplicate testing code for this function. Finally, we add safety checks for directory saving to ensure that we don't attempt to save to directories that do not exist.

Refactoring dimensionality_reduction

---

ark/segmentation/marker_quantification.py
ark/segmentation/marker_quantification_test.py
templates/Deepcell_Postprocessing.ipynb

Addresses and closes #185.
Rename some functions in `marker_quantification.py` to something more understandable. Split up the test functions in `marker_quantification_test.py`.

Refactor marker quantification

---

.travis.yml

Bugfix to temporarily comment out the line in travis that's causing failures

Remove setup.py install

---

ark/utils/deepcell_service_utils.py

Cleans and clarifies progress bar in deepcell upload notebook
Closes #382

removes units from progress bar, and clarifies meaning

---

ark/phenotyping/create_som_matrix.R
ark/phenotyping/run_trained_som.R
ark/phenotyping/som_utils.py
ark/phenotyping/som_utils_test.py

Addresses and closes #395. We've learned that the 99.9% normalized values on a subset provide a very good estimate for the entire dataset. To ensure consistency, we ensure that 99.9% normalization during cluster time uses the same values as computed during training time.
We add another intermediate feather file: `norm_vals.feather`, to the mix.

Use subsetted 99.9% normalized values as ground truth

---

docs/_rtd/data_types.md
templates/Segment_Image_Data.ipynb

Closes #393 and closes #398. A lot of morphology metrics have been added to the cell table, so we should explain what each of the metrics are computing.
We add the description to `data_types.md`.

Update cell table description to include morphology metrics

---

ark/settings.py
ark/spLDA/processing.py
ark/utils/misc_utils.py
ark/utils/misc_utils_test.py
ark/utils/spatial_lda_utils.py
ark/utils/spatial_lda_utils_test.py
requirements.txt

This PR merges functions, helper scripts, and tests for the initial data processing steps in spatial-lda analysis.  The PR is intentionally small to allow for easier integration into the spatial-LDA branch. 
Three main functions were added [format_cell_table(), featurize_cell_table(), create_difference_matrices()] which create the necessary data structures to be passed to the existing spatial_lda library.  For each processing function, an argument-checking helper function was added in spatial_lda_utils.py, and tests for the helper functions are included in spatial_lda_utils_test.py.
No tests are currently implemented for the three processing functions specifically.

Processing branch

---

docs/_rtd/windows_setup.md

Closes #562.
Adding an external drive on WSL is a bit ambiguous, so there is now documentation on how to specifically mount an external drive.
Added brief documentation based on @ackagel 's issue.
None.

adding windows external docs

---

ark/utils/io_utils.py
ark/utils/io_utils_test.py

add .json and .bin file compatibility to remove_file_extensions()

---

ark/analysis/spatial_analysis.py

Laughably small pr. Here's a preview of the progress bar in the example notebook, for reference:

Batching progress bar for spatial enrichment

---

ark/analysis/spatial_analysis.py
ark/analysis/spatial_analysis_test.py
ark/utils/spatial_analysis_utils.py
ark/utils/spatial_analysis_utils_test.py
ark/utils/test_utils.py

Adds feature distance columns to spatial enrichment analysis.
Appends rows to cell table representing desired 'feature', and appends row+col to distance matrix representing said feature.  Also adds basic coverage test.
Testing for positive, negative, and neutral enrichments.  This will be covered in a post-workshop pr

Enrichment distance hack

---

README.md

Closes #682.
Added a link to the playlist at the top of overview section of the README. Added links to talks with their timestamp (i.e. Session V - Part I Segmentation @ 3:50).
None ATM.

Workshop Links

---

ark/phenotyping/cell_cluster_utils.py
ark/phenotyping/pixel_cluster_utils.py
ark/phenotyping/pixel_consensus_cluster.R
ark/phenotyping/run_pixel_som.R

Closes #695. The way R parallel processing runs, sometimes the number of cores needs to be adjusted to prevent failures.
Add a customizable argument `ncores` to the pixel SOM assignment and pixel consensus clustering functions, which get passed to their respective R scripts.
Is this a function we want to add for pixel data preprocessing and pixel meta cluster renaming?

Allow user to set number of cores for R functions

---

ark/segmentation/marker_quantification.py

Closes #646. 
Update logic to only load nuclear image data if `nuclear_counts=True`.

Nuclear counts loading

---

ark/analysis/spatial_analysis.py
ark/analysis/spatial_analysis_test.py
ark/utils/notebooks_test.py
ark/utils/notebooks_test_utils.py
templates/1_Segment_Image_Data.ipynb
templates/2_Cluster_Pixels.ipynb
templates/3_Cluster_Cells.ipynb
templates/4_Post_Clustering.ipynb

Closes #765. 
Adjusted the notebook test suite. 1 test class for each notebook, with one test per tagged code cell in the notebooks. Split `base_dir` assignments to their own cell before the rest of the other path setup statements.
In the future construct a small dataset for all the notebook tests. In addition add tests for neighborhood analysis, pairwise spatial enrichment, image_stitching, and for the LDA notebooks.

Testbook Adjustments

---

setup.py
start_docker.sh

Creates a new release.
Bumped the version from `v0.4.3` to `v0.4.4`.
None ATM.

Next Release - v0.4.4

---

README.md
docs/_rtd/data_types.md

Closes #789.
Links the `data_types.md` document in the README. Added an example column header for the cell table. Added instructions about adjusting column header values for the cell table if necessary.

Cell Table Assumptions

---

README.md

This random Greenwald guy is listed as co-first on the Pixie paper
Removed the interloper

Fix Pixie authorship

---

templates/1_Segment_Image_Data.ipynb
templates/2_Cluster_Pixels.ipynb
templates/3_Cluster_Cells.ipynb
templates/4_Post_Clustering.ipynb

Closes #821.
Added a small blurb to each of the example dataset sections on when to set `overwrite_existing` to `False` / `True`.
N/A.

Example Dataset - Adding more info to Overwrite Existing

---

ark/phenotyping/post_cluster_utils.py

Closes #835.
Removed duplicate FOV loading in `create_mantis_project`.
N/A.

Removed duplicate mantis fov loading

---

README.md
setup.py
start_docker.sh

Closes #872.
Makes changes for a new release with the pyFlowSOM changes (v0.5.0).
Adjusted the versioning.

Next Release v0.5.0

---

.dockerignore
.github/workflows/docker.yml
Dockerfile
README.md
docs/_rtd/development.md
start_docker.sh
tox.ini

Changes needed for a new release. Also, an opportunity to test the release workflow, and find any straggling issues.
Added the CI workflow in the README.md

Next Release - v0.5.2

---

templates/2_Pixie_Cluster_Pixels.ipynb
templates/3_Pixie_Cluster_Cells.ipynb

Edit text in the Pixie notebooks. No code changes.
Typing.
I think we are ready to pin the version for the paper after merging this one and https://github.com/angelolab/ark-analysis/pull/913.

Pixie notebook text changes

---

README.md
start_docker.sh

Per @ngreenwald we actually want to make this our next major patch. This is for Candace's review cycle.
Some things we had to take out for Candace's review cycle (channel and pixel thresh normalization for Pixie preprocessing), we'll have to put them back after that's complete.

Next Release - v0.6.0

---

.gitignore
pyproject.toml

Closes #952. Should fix GitHub Actions CI tests, and running tests locally.
Pinned `ipywidgets` to `8.0.0`.
N/A. However, we should revisit and unpin it in a few weeks when it's fixed in a separate pr.

Pinned `ipywidgets`

---

.github/workflows/build.yml
.github/workflows/test.yml
README.md
start_docker.sh

Closes #957.
Added pip installation instructions.
Bumped the `VERSION` in `start_docker.sh`. Did some minor aesthetic changes to the names of the GitHub Actions jobs.
N/A.

Next Release - v0.6.2

---

README.md

Updates the citation information with a link to ark, and general text about which papers might be useful

Update citation information

---

.github/workflows/ci.yml
README.md
start_docker.sh

Updates files for a new release. updates coveralls to `v2`.
Changed the `VERSION` to `v0.6.3`.
Make a new release!

Next Release v0.6.3

---

src/ark/utils/plot_utils.py

Closes #967.
Added `interpolation='nearest'` to the plt.imshow() call.
NA

Kmeans plotting cell border fix

---

environment.yml

Adds a Conda environment file for this week's environment codecademy.
The environment file contains the `conda-forge` channel, and installs the local version of ark.
N/A.

Added Conda environment file

---

src/ark/analysis/cell_neighborhood_stats.py
src/ark/analysis/neighborhood_analysis.py
src/ark/analysis/spatial_analysis_utils.py

Closes #1019. 
Adds progress bars for neighbors matrix generation, diversity analysis, and cell distance analysis. Also adds a fov description to the distance matrix progress bar.
Use tdqm package.
Any suggestions for other places in ark that could use a progress bar?

Add progress bars in Cell Neighbors Analysis notebook

---

README.md
start_docker.sh

Make a new release, mostly to account for re-adding of channel and pixel normalization to the Pixie preprocessing pipeline. This needed to be separate from v0.6.4 for Candace's paper.
Update references in `start_docker.sh` and `README.md`.

Bump to v0.6.5

---

pyproject.toml

Set the alpineer version to the new release, which includes a fix to prevent images from rotating during OME tiff conversion.
NA

Apineer v0.1.10

---

README.md
start_docker.sh

`ezSeg` is a major addition to the pipeline, so it needs a major release.
Update version in `README.md` and `start_docker.sh`.

Bump to v0.7.0

---

README.md

Update the release version in the readme.
Then we can make the new ark release public.

Update release version in readme

---

.github/workflows/build.yml
.github/workflows/release.yml

Makes some small changes to permissions for the release workflow dispatching the build and test workflows..

Updated CI Workflows for Releases
